initData Correction : error in template, so initialize with empty values
pkp/textEditorExtras pull request #19
Opened 2023-04-11 08:40 UTC by mathiasv27

Hi,
I've made a little correction in iniData method. An error occured in 3.3.0.14, in settings.tpl : PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given
So the "additions" var is initialized with empty arrays if datas are not present.

2023-04-11 08:57 UTC, NateWr commented
Thanks @mathiasv27! It looks like your code editor has applied formatting across the file. Can you redo your PR so that only the bug fix is applied?

Also, can you remove the changes to the French `.po` file? All translations are applied through weblate. You can make changes for this plugin here: https://translate.pkp.sfu.ca/projects/plugins/texteditorextras/

2023-04-11 09:38 UTC, mathiasv27 commented
Ok, thanks ! I've reverted my commit and pushed only the bug fix, is that ok or do I have to cancel this request and redo a PR ?

2023-04-11 11:38 UTC, NateWr requested changes
Thanks @mathiasv27! The revert commit is fine. I'll squash it all before I merge. A few comments here about code syntax, but otherwise looks good. :+1:

2023-04-11 11:38 UTC, NateWr commented on TextEditorExtrasSettingsForm.inc.php
> +    public function initData()
In `stable-3_3_0` we are still using tabs not spaces. Can you convert to tabs so we're consistent with other code in this file?

2023-04-11 11:38 UTC, NateWr commented on TextEditorExtrasSettingsForm.inc.php
> +            );
Please use the short array syntax, `[]`, rather than the longer one, `array()` for all array declarations here.

2023-04-11 11:38 UTC, NateWr commented on TextEditorExtrasSettingsForm.inc.php
> +            foreach ($this->plugin->getSetting($contextId, 'additions') as $key => $value) {
Instead of looping over each item, I think you can use `array_merge`:

```php
$settings = $this->plugin->getSetting(...);
if (is_array($settings)) {
	$additions = array_merge($additions, $settings);
}
```

2023-04-11 11:45 UTC, mathiasv27 commented on TextEditorExtrasSettingsForm.inc.php
> +            foreach ($this->plugin->getSetting($contextId, 'additions') as $key => $value) {
I tried array_merge before doing that, but it doesn't work because arrays are empty

2023-04-11 14:01 UTC, NateWr commented on TextEditorExtrasSettingsForm.inc.php
> +            foreach ($this->plugin->getSetting($contextId, 'additions') as $key => $value) {
Can you try `array_merge_recursive`?

2023-04-11 14:02 UTC, NateWr commented on TextEditorExtrasSettingsForm.inc.php
> +			"masthead" => ["description" => [] ],
Just one extra space at the end here: `[] ]` should be `[]]`.

2023-04-11 14:18 UTC, mathiasv27 commented on TextEditorExtrasSettingsForm.inc.php
> +            foreach ($this->plugin->getSetting($contextId, 'additions') as $key => $value) {
Better with that, thx

2023-04-11 14:25 UTC, NateWr commented
That's all my comments address.  @mathiasv27 are you ready for me to merge this and port it to `main`?

2023-04-11 14:27 UTC, mathiasv27 commented
It's ok for me !

2023-04-17 08:48 UTC, NateWr requested changes

2023-04-17 08:48 UTC, NateWr commented on TextEditorExtrasSettingsForm.inc.php
> +			$additions = array_merge_recursive($additions, $settings);
`$this->plugin->getSetting()` might not return an array, so can you check that it's an array before passing it to `array_merge_recursive()`?

```php
if (is_array($settings)) {
```

Thanks!

2023-05-16 11:10 UTC, mathiasv27 commented
Hi,
Is it possible to merge, or is something missing ?
Thanks a lot !

2023-05-19 01:00 UTC, asmecher commented
@mathiasv27, I think this is actually a duplicate of https://github.com/pkp/pkp-lib/issues/8064, which has already been fixed with additions to the template (rather than the .php code). What version of the plugin are you using?

2023-05-22 06:15 UTC, mathiasv27 commented
I'm using the last version on stable-3_3_0 : 1.0.0.2 . The additions to the template, such as `if is_array($additions.masthead.description)` didn't work, because if $additions or $additions.masthead is not initialized as an array, it throws an error...

2023-05-23 22:40 UTC, asmecher commented
@mathiasv27, ah! I think that's a mistake in using `is_array` instead of `isset`. Using `isset` instead would suppress the warning. Does that solve the problem in your case?

Your proposed solution of pre-initializing in PHP is also 100% valid, but with the additions already started in the template side, I'd favour continuing there. If you do prefer the PHP-side approach, please feel free to update the PR, but do also remove the template `is_array` calls in the process.

2023-05-24 08:45 UTC, mathiasv27 commented
Ok, that's better: I replaced is_array by isset and removed the is_array tests in the template. I prefer this approach indeed: sending a formatted and tested array of values to the template is, from my modest point of view, preferable to doing existence tests in a template :)
Thank you so much ! We have to present to users on our staging server shortly, do you think this can be merged soon?

2023-06-06 22:37 UTC, merged

2023-06-06 22:40 UTC, asmecher commented
@mathiasv27, agreed, this is a better solution. Thanks for working through it with us (and sorry for the delay)! I've merged it to `stable-3_3_0` and forward-ported it to `main` for the forthcoming 3.4.0 branch.

2023-06-07 07:03 UTC, mathiasv27 commented
> @mathiasv27, agreed, this is a better solution. Thanks for working through it with us (and sorry for the delay)! I've merged it to `stable-3_3_0` and forward-ported it to `main` for the forthcoming 3.4.0 branch.

Thanks a lot, Alec ! Don't worry about the delay, I understand ;)